# Generated by Django 5.2 on 2025-09-05 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ENV_VAR", "Environment Variable"),
                            ("PROMPT", "Code/AI Prompt"),
                            ("DOC_LINK", "Documentation Link"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("DEV", "Development"),
                            ("STAGING", "Staging"),
                            ("PROD", "Production"),
                        ],
                        default="DEV",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("key", models.CharField(blank=True, max_length=255)),
                ("value", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "kind"],
                        name="artifacts_a_workspa_4e1932_idx",
                    ),
                    models.Index(
                        fields=["workspace", "environment"],
                        name="artifacts_a_workspa_353865_idx",
                    ),
                    models.Index(
                        fields=["kind", "-updated_at"],
                        name="artifacts_a_kind_44ae0d_idx",
                    ),
                    models.Index(
                        fields=["workspace", "kind", "environment"],
                        name="artifacts_a_workspa_8f27bb_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("kind", "ENV_VAR"), models.Q(("key", ""), _negated=True)
                        ),
                        fields=("workspace", "kind", "key", "environment"),
                        name="unique_env_var_key_per_workspace_environment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("kind__in", ["PROMPT", "DOC_LINK"]),
                            models.Q(("title", ""), _negated=True),
                        ),
                        fields=("workspace", "kind", "title", "environment"),
                        name="unique_title_per_workspace_environment_and_kind",
                    ),
                ],
            },
        ),
    ]
